### ISSUE TITLE
Uncaught exception 'Exception' for adddb

### ISSUE THREAD

**Issue by lightwaxx** [CpanelInc/xmlapi-php#23]
Fatal error:  Uncaught exception 'Exception' with message 'curl_exec threw error "Failed to connect to xxx.xxx.xxx.xxx port 2082: Connection refused" for https://xxx.xxx.xxx.xxx:2083/xml-api/cpanel?user=xxxxxxx&cpanel_xmlapi_module=mysql&cpanel_xmlapi_func=adddb&cpanel_xmlapi_apiversion=1&arg-0=ihhemrl7_sitedb' in /home/xxxxxxx/public_html/includes/hooks/xmlapi-copy-2009.php:692

**Comment by naptastic** [comment]
Hello,

A "Connection Refused" error indicates that your cPanel server is not listening on port 2082, or is blocked in a firewall someplace. Please contact your hosting provider for assistance.

**Comment by lightwaxx** [comment]
Issue is not the port, issue is when I try and run $xmlapi->api1_query($params['params']['username'], "mysql", "adddb", array($params['params']['username']. '_' .$databasename))) function to create a database. This is when I get that error

**Comment by lightwaxx** [comment]
This is still open

**Comment by lightwaxx** [comment]
Issue with $xmlapi->api1_query($cpaneluser, "mysql", "adddb", array($databasename)). This is the bit not working, not the port

**Comment by davidneimeyer** [comment]
why is the port reported in the exception message different that the port in the URL that is being use for the cURL connection?

**Comment by lightwaxx** [comment]
Is I comment this bit out $xmlapi->api1_query($cpaneluser, "mysql", "adddb", array($databasename)) everything runs and account is created but the database is not created

**Comment by lightwaxx** [comment]
You were right, the issue was a port issue. Thanks for the help. Its working perfectly
